// lib/carLogos.ts
const logoMap: Record<string, string> = {
    "Abarth": "/Logos/abarth.webp",
    "Acura": "/Logos/acura.webp",
    "Aiways": "/Logos/aiways.webp",
    "Aixam": "/Logos/aixam.webp",
    "Alfa Romeo": "/Logos/alfa_romeo.webp",
    "Alpina": "/Logos/alpina.webp",
    "Alpine": "/Logos/alpine.webp",
    "ARI Motors": "/Logos/ari_motors.webp",
    "Aston Martin": "/Logos/aston_martin.webp",
    "Audi": "/Logos/audi.webp",
    "Bentley": "/Logos/bentley.webp",
    "BMW": "/Logos/bmw.webp",
    "Bugatti": "/Logos/bugatti.webp",
    "BYD": "/Logos/byd.webp",
    "Cadillac": "/Logos/cadillac.webp",
    "Chevrolet": "/Logos/chevrolet.webp",
    "Chrysler": "/Logos/chrysler.webp",
    "Citroen": "/Logos/citroen.webp",
    "Cupra": "/Logos/cupra.webp",
    "Dacia": "/Logos/dacia.webp",
    "Daewoo": "/Logos/daewoo.webp",
    "Daihatsu": "/Logos/daihatsu.webp",
    "DFSK": "/Logos/dfsk.webp",
    "Dodge": "/Logos/dodge.webp",
    "Dongfeng": "/Logos/dongfeng.webp",
    "Dr Automobiles": "/Logos/dr_automobiles.webp",
    "DS Automobiles": "/Logos/ds_automobiles.webp",
    "Ferrari": "/Logos/ferrari.webp",
    "Fiat": "/Logos/fiat.webp",
    "Fisker": "/Logos/fisker.webp",
    "Ford": "/Logos/ford.webp",
    "Genesis": "/Logos/genesis.webp",
    "GMC": "/Logos/gmc.webp",
    "Honda": "/Logos/honda.webp",
    "Hummer": "/Logos/hummer.webp",
    "Hyundai": "/Logos/hyundai.webp",
    "Infiniti": "/Logos/infiniti.webp",
    "Isuzu": "/Logos/isuzu.webp",
    "Iveco": "/Logos/iveco.webp",
    "Jaguar": "/Logos/jaguar.webp",
    "Jeep": "/Logos/jeep.webp",
    "Kia": "/Logos/kia.webp",
    "Lada": "/Logos/lada.webp",
    "Lamborghini": "/Logos/lamborghini.webp",
    "Lancia": "/Logos/lancia.webp",
    "Land Rover": "/Logos/land_rover.webp",
    "Leapmotor": "/Logos/leapmotor.webp",
    "Lexus": "/Logos/lexus.webp",
    "Ligier": "/Logos/ligier.webp",
    "Lincoln": "/Logos/lincoln.webp",
    "Lotus": "/Logos/lotus.webp",
    "Lucid": "/Logos/lucid.webp",
    "Lynk & Co": "/Logos/lynk_and_co.webp",
    "Mahindra": "/Logos/mahindra.webp",
    "Maserati": "/Logos/maserati.webp",
    "Maybach": "/Logos/maybach.webp",
    "Mazda": "/Logos/mazda.webp",
    "McLaren": "/Logos/mclaren.webp",
    "Mercedes-Benz": "/Logos/mercedes_benz.webp",
    "MG": "/Logos/mg.webp",
    "MINI": "/Logos/mini.webp",
    "Mitsubishi": "/Logos/mitsubishi.webp",
    "Morgan": "/Logos/morgan.webp",
    "NIO": "/Logos/nio.webp",
    "Nissan": "/Logos/nissan.webp",
    "Opel": "/Logos/opel.webp",
    "Peugeot": "/Logos/peugeot.webp",
    "Polestar": "/Logos/polestar.webp",
    "Porsche": "/Logos/porsche.webp",
    "RAM": "/Logos/ram.webp",
    "Renault": "/Logos/renault.webp",
    "Rolls-Royce": "/Logos/rolls_royce.webp",
    "Saab": "/Logos/saab.webp",
    "Seat": "/Logos/seat.webp",
    "Skoda": "/Logos/skoda.webp",
    "Smart": "/Logos/smart.webp",
    "Ssangyong": "/Logos/ssangyong.webp",
    "Subaru": "/Logos/subaru.webp",
    "Suzuki": "/Logos/suzuki.webp",
    "Tesla": "/Logos/tesla.webp",
    "Toyota": "/Logos/toyota.webp",
    "Vinfast": "/Logos/vinfast.webp",
    "Volkswagen": "/Logos/volkswagen.webp",
    "Volvo": "/Logos/volvo.webp",
    "Wiesmann": "/Logos/wiesmann.webp"
    // ...add more as needed
  };
  export default logoMap;
  